[package]
name = "gccjit-sys"
version = "0.3.0"
authors = ["Yuri Katsuki <yuri@katsuki.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.49"